# Generated by Django 5.1.6 on 2025-02-25 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preference', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('low_carb', 'Low Carb'), ('balanced', 'Balanced'), ('other', 'Other')], default='balanced', max_length=20)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('preferred_meals', models.JSONField(blank=True, default=list)),
                ('calorie_goal', models.IntegerField(default=2000, help_text='Daily calorie intake goal in kcal')),
                ('protein_percentage', models.FloatField(default=20.0, help_text='Protein percentage of daily intake')),
                ('carbs_percentage', models.FloatField(default=50.0, help_text='Carbs percentage of daily intake')),
                ('fat_percentage', models.FloatField(default=30.0, help_text='Fat percentage of daily intake')),
                ('health_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance')], default='maintenance', max_length=20)),
                ('cuisine_preferences', models.JSONField(blank=True, default=list, help_text='Preferred cuisine types')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
