# Generated by Django 5.1.6 on 2025-02-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
